[phases.setup]
cmds = [
    "mkdir -p storage/database",
    "touch storage/database/database.sqlite"
]

[phases.install]
cmds = [
    "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev"
]

[phases.build]
cmds = [
    "php artisan key:generate",
    "php artisan migrate --force",
    "php artisan db:seed --force",
    "php artisan optimize"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[environments]
APP_ENV = "production"
APP_DEBUG = "false"
DB_CONNECTION = "sqlite"
DB_DATABASE = "/app/storage/database/database.sqlite"
