[build]
builder = "nixpacks.toml"
buildCommand = "mkdir -p storage/database && touch storage/database/database.sqlite && php artisan migrate --force && php artisan db:seed --force"
startCommand = 'php artisan serve --host=0.0.0.0 --port=$PORT'

[build.environment]
APP_ENV = "production"
APP_DEBUG = false
APP_KEY = "base64:YOUR_APP_KEY_HERE"
DB_CONNECTION = "sqlite"
DB_DATABASE = "/app/storage/database/database.sqlite"

[deploy]
startCommand = 'php artisan serve --host=0.0.0.0 --port=$PORT'

[deploy.variables]
APP_ENV = "production"
APP_DEBUG = false
DB_CONNECTION = "sqlite"
DB_DATABASE = "/app/storage/database/database.sqlite"
